# monitoring/prometheus.yml
global:
  scrape_interval: 15s # Con qué frecuencia Prometheus "raspa" las métricas
  evaluation_interval: 15s # Con qué frecuencia evalúa las reglas de alerta

# Carga las reglas de alerta (las crearemos en Sprint 4)
# rule_files:
#  - "alert_rules.yml" 

scrape_configs:
  - job_name: 'billetera_bank_a_services'
    # Cómo Prometheus encuentra nuestros servicios
    static_configs:
      - targets: [
          'gateway_service:8080',  # Puerto INTERNO del Dockerfile
          'auth_service:8000',     # Puerto INTERNO del Dockerfile
          'balance_service:8000',  # Puerto INTERNO del Dockerfile
          'ledger_service:8000',   # Puerto INTERNO del Dockerfile
          'mock_bankb:8000'        # Puerto INTERNO del Dockerfile
        ]
    # Todos exponen métricas en la ruta /metrics
    metrics_path: /metrics

# Dónde está Alertmanager (para enviar alertas)
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] # Nombre del servicio y puerto interno